# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tribal < Formula
  desc "Tribal CLI - Graph-based development workflow"
  homepage "https://github.com/bodiman/tribal-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Darwin_x86_64.tar.gz"
      sha256 "901e6e22e051db370763f729e519e33b56b28f79c6b0e7746680bbbf4733e9a4"

      def install
        bin.install "tribal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Darwin_arm64.tar.gz"
      sha256 "e4f0baf651ae2c582e252791d4036998ac47bb238e4820d8624eef696aee41ef"

      def install
        bin.install "tribal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Linux_x86_64.tar.gz"
      sha256 "92a2c9da39b4d3a7b682d41e89e6af55a2eec32d9018c0ffa42192da8e04ff3f"
      def install
        bin.install "tribal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Linux_arm64.tar.gz"
      sha256 "40fa29645fd9e86d781ac7c1db065a18c6830bfe53126674d01be36702f6f43a"
      def install
        bin.install "tribal"
      end
    end
  end
end
