# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tribal < Formula
  desc "Tribal CLI - Graph-based development workflow"
  homepage "https://github.com/bodiman/tribal-cli"
  version "1.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.8/tribal-cli_Darwin_x86_64.tar.gz"
      sha256 "6d4b894042a335403b83f3d87cfa849d8386bd12f755a8af9dd920bee9925e0e"

      def install
        bin.install "tribal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.8/tribal-cli_Darwin_arm64.tar.gz"
      sha256 "3764c8c19f8972e4c35c6041e886eba901e5b7c9c338ed6e0202202172bade15"

      def install
        bin.install "tribal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.8/tribal-cli_Linux_x86_64.tar.gz"
      sha256 "3a3b3e84b305f4c6991ac467c31b7230cb1a0599e621f9dac279c294e3f81baf"
      def install
        bin.install "tribal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.8/tribal-cli_Linux_arm64.tar.gz"
      sha256 "b02907d2bbc9c13bf6ee03dfca125280aeb0d9d09d5a43e82b0cdee5d9ea7f48"
      def install
        bin.install "tribal"
      end
    end
  end
end
