# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tribal < Formula
  desc "Tribal CLI - Graph-based development workflow"
  homepage "https://github.com/bodiman/tribal-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Darwin_x86_64.tar.gz"
      sha256 "894bdce878218a55f997b20b9da61d200df7e20da1eb854cd72e559e858441b3"

      def install
        bin.install "tribal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Darwin_arm64.tar.gz"
      sha256 "8e87380526a207bd62bc5cba47d36cd9adbbac115141ccdf7a6072368ff62bb0"

      def install
        bin.install "tribal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Linux_x86_64.tar.gz"
      sha256 "41c00b067c8bfa8f79e55ffe00ef99e138d1688fb86fff57aa099be297a5557f"
      def install
        bin.install "tribal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bodiman/tribal-cli/releases/download/v1.0.3/tribal-cli_Linux_arm64.tar.gz"
      sha256 "287ae752c1f121ef6c4ad49cdaaaf345cdbc5fea9506b31ee37a4e4e89780866"
      def install
        bin.install "tribal"
      end
    end
  end
end
